// The whole /datum/unit_test framework only exists in a UNIT_TESTS (or SPACEMAN_DMM) build, see
// the matching #if wrapping code/modules/unit_tests/_unit_tests.dm's own internal test includes.
#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/**
 * Regenerates modular_zzmeta/code/modules/clothing/underwear/generated/underwear_items.dm from
 * the live /datum/sprite_accessory/clothing/{underwear,bra,undershirt,socks} type tree, and fails
 * if the checked-in generated file doesn't match, so new accessory styles can't be added without
 * also regenerating their corresponding real item.
 */
/datum/unit_test/underwear_items
	var/list/lines = list()

/datum/unit_test/underwear_items/Run()
	lines = list()
	lines += "/* This file is automatically generated by the unit test. Do not edit it manually."
	lines += " * Generating this file is done by running the unit test locally, see the fail message for more details."
	lines += " * All items corresponding to /datum/sprite_accessory/clothing/{underwear,bra,undershirt,socks} should be here."
	lines += " */"
	lines += ""

	lines += "// ==== underwear ===="
	for(var/datum/sprite_accessory/clothing/underwear/accessory_type as anything in subtypesof(/datum/sprite_accessory/clothing/underwear))
		add_item_lines(accessory_type, /datum/sprite_accessory/clothing/underwear, /datum/sprite_accessory/clothing/underwear::icon, /obj/item/clothing/underwear/underwear, is_underwear = TRUE)
	lines += ""

	lines += "// ==== bra ===="
	for(var/datum/sprite_accessory/clothing/bra/accessory_type as anything in subtypesof(/datum/sprite_accessory/clothing/bra))
		add_item_lines(accessory_type, /datum/sprite_accessory/clothing/bra, /datum/sprite_accessory/clothing/bra::icon, /obj/item/clothing/underwear/bra)
	lines += ""

	lines += "// ==== undershirt ===="
	for(var/datum/sprite_accessory/clothing/undershirt/accessory_type as anything in subtypesof(/datum/sprite_accessory/clothing/undershirt))
		add_item_lines(accessory_type, /datum/sprite_accessory/clothing/undershirt, /datum/sprite_accessory/clothing/undershirt::icon, /obj/item/clothing/underwear/undershirt, is_undershirt = TRUE)
	lines += ""

	lines += "// ==== socks ===="
	for(var/datum/sprite_accessory/clothing/socks/accessory_type as anything in subtypesof(/datum/sprite_accessory/clothing/socks))
		add_item_lines(accessory_type, /datum/sprite_accessory/clothing/socks, /datum/sprite_accessory/clothing/socks::icon, /obj/item/clothing/underwear/socks)
	lines += ""

	var/output_file = "[lines.Join("\n")]\n"
	rustg_file_write(output_file, "data/underwear_items.dm")
	var/current = file2text('modular_zzmeta/code/modules/clothing/underwear/generated/underwear_items.dm')
	if(current == output_file)
		return

	TEST_FAIL("Underwear items generated file is out of date. Run locally by enabling unit tests, (see _compile_options.dm) and copy 'data/underwear_items.dm' to 'modular_zzmeta/code/modules/clothing/underwear/generated/underwear_items.dm'")

/datum/unit_test/underwear_items/proc/add_item_lines(datum/sprite_accessory/clothing/accessory_type, base_accessory_type, default_icon, base_item_type, is_underwear = FALSE, is_undershirt = FALSE)
	if(accessory_type == base_accessory_type)
		return // abstract base itself

	var/leaf_name = replacetext("[accessory_type]", "[base_accessory_type]/", "")
	if(leaf_name == "nude")
		return

	var/acc_name = initial(accessory_type.name)
	var/acc_icon_state = initial(accessory_type.icon_state)
	if(!acc_name || !acc_icon_state)
		return

	var/item_type_name = replacetext(leaf_name, "/", "_")
	lines += "[base_item_type]/[item_type_name]"
	lines += "\tname = \"[acc_name]\""
	lines += "\ticon_state = \"[acc_icon_state]\""

	var/acc_icon = initial(accessory_type.icon)
	if(acc_icon != default_icon)
		lines += "\ticon = '[acc_icon]'"
		lines += "\tworn_icon = '[acc_icon]'"
		lines += "\tlefthand_file = '[acc_icon]'"
		lines += "\trighthand_file = '[acc_icon]'"

	var/acc_gender = initial(accessory_type.gender)
	if(acc_gender == MALE)
		lines += "\tgender = MALE"
	else if(acc_gender == FEMALE)
		lines += "\tgender = FEMALE"

	if(initial(accessory_type.use_static))
		lines += "\tuse_static = TRUE"

	if(is_underwear)
		var/datum/sprite_accessory/clothing/underwear/underwear_type = accessory_type
		if(initial(underwear_type.has_digitigrade) || initial(underwear_type.digi_icon_state))
			lines += "\thas_digitigrade = TRUE"
		if(initial(underwear_type.hides_breasts))
			lines += "\tbody_parts_covered = GROIN | CHEST"

	if(is_undershirt)
		var/datum/sprite_accessory/clothing/undershirt/undershirt_type = accessory_type
		if(initial(undershirt_type.hides_groin))
			lines += "\tbody_parts_covered = CHEST | ARMS | GROIN"

	lines += ""

#endif
